### ISSUE TITLE
Imposter

### ISSUE THREAD

**Issue by HelloooJoe** [ChrisGrindereng/SampleCQRS#1]
Why are you stealing someone else's repo and passing it off as your own??? Take a look at 
https://github.com/exceptionnotfound/SampleCQRS

you fraud!

**Comment by ChrisGrindereng** [comment]
I did not intend to pass this code of as my own. This was built from expectionnotfound's awesome tutorial on CQRS so I could become familiar with domain driven design for a new job. To avoid future confusion for anyone else looking at this I have now attached a readme that attributes the code and links to the tutorial.
